const fs = require("fs");
const path = require("path");
const { Document, Packer, Paragraph, TextRun } = require("docx");

const doc = new Document({
  creator: "HYTEK",
  title: "Test",
  sections: [{
    children: [
      new Paragraph({ children: [new TextRun({ text: "If you can read this, .docx works on your machine.", bold: true })] }),
      new Paragraph({ children: [new TextRun("Generated by node " + process.version + " · docx package OK.")] }),
    ],
  }],
});

const out = path.join(__dirname, "..", "docs", "TEST_minimal.docx");
Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync(out, buf);
  console.log("Wrote", out, `(${buf.length} bytes)`);
});
